//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.06 at 01:34:36 AM IRST 
//


package com.jalian.soap_crud.dto;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jalian.soap_crud.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateStudentRequest_QNAME = new QName("dto.soap-crud.jalian.com", "createStudentRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jalian.soap_crud.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StudentDto }
     * 
     */
    public StudentDto createStudentDto() {
        return new StudentDto();
    }

    /**
     * Create an instance of {@link GetStudentByIdRequest }
     * 
     */
    public GetStudentByIdRequest createGetStudentByIdRequest() {
        return new GetStudentByIdRequest();
    }

    /**
     * Create an instance of {@link GetStudentByIdResponse }
     * 
     */
    public GetStudentByIdResponse createGetStudentByIdResponse() {
        return new GetStudentByIdResponse();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link DeleteStudentRequest }
     * 
     */
    public DeleteStudentRequest createDeleteStudentRequest() {
        return new DeleteStudentRequest();
    }

    /**
     * Create an instance of {@link DeleteCourseRequest }
     * 
     */
    public DeleteCourseRequest createDeleteCourseRequest() {
        return new DeleteCourseRequest();
    }

    /**
     * Create an instance of {@link AddCourseToStudentRequest }
     * 
     */
    public AddCourseToStudentRequest createAddCourseToStudentRequest() {
        return new AddCourseToStudentRequest();
    }

    /**
     * Create an instance of {@link CourseDto }
     * 
     */
    public CourseDto createCourseDto() {
        return new CourseDto();
    }

    /**
     * Create an instance of {@link AddCourseToStudentResponse }
     * 
     */
    public AddCourseToStudentResponse createAddCourseToStudentResponse() {
        return new AddCourseToStudentResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudentDto }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StudentDto }{@code >}
     */
    @XmlElementDecl(namespace = "dto.soap-crud.jalian.com", name = "createStudentRequest")
    public JAXBElement<StudentDto> createCreateStudentRequest(StudentDto value) {
        return new JAXBElement<StudentDto>(_CreateStudentRequest_QNAME, StudentDto.class, null, value);
    }

}
