//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.06 at 01:34:36 AM IRST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "dto.soap-crud.jalian.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jalian.soap_crud.dto;
